name: segobe_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - scipy
  - scikit-image
  - matplotlib
  - tifffile
  - git
  - pip
  - pip:
    - git+https://github.com/schapirolabor/segobe.git